# Generated by Django 5.2.5 on 2025-09-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote_page', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
