# Generated by Django 5.2.5 on 2025-09-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_page', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
