# Generated by Django 5.2.5 on 2025-09-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_page', '0004_tablequote'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablequote',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
